from __future__ import annotations

from fastapi import APIRouter
from app.controllers import admin_controller as controller

router = APIRouter(prefix='/api/admin', tags=["admin"])

router.add_api_route("/seed", endpoint=controller.seed_admin, methods=["GET"])
router.add_api_route("/profile", endpoint=controller.get_admin_profile, methods=["GET"])
router.add_api_route("/profile", endpoint=controller.update_admin_profile, methods=["PUT"])
router.add_api_route("/change-password", endpoint=controller.change_password, methods=["PUT"])
router.add_api_route("/dashboard", endpoint=controller.dashboard, methods=["GET"])
router.add_api_route("/manage", endpoint=controller.get_admins, methods=["GET"])
router.add_api_route("/manage", endpoint=controller.create_admin_user, methods=["POST"])
router.add_api_route("/manage/{id}", endpoint=controller.update_admin_user, methods=["PUT"])
router.add_api_route("/manage/{id}", endpoint=controller.delete_admin_user, methods=["DELETE"])
router.add_api_route("/donors", endpoint=controller.donors, methods=["GET"])
router.add_api_route("/donors", endpoint=controller.create_donor, methods=["POST"])
router.add_api_route("/donor/{id}", endpoint=controller.donor_by_id, methods=["GET"])
router.add_api_route("/donor/{id}", endpoint=controller.update_donor, methods=["PUT"])
router.add_api_route("/donor/{id}", endpoint=controller.delete_donor, methods=["DELETE"])
router.add_api_route("/facilities", endpoint=controller.facilities, methods=["GET"])
router.add_api_route("/facilities", endpoint=controller.create_facility, methods=["POST"])
router.add_api_route("/facility/{id}", endpoint=controller.update_facility, methods=["PUT"])
router.add_api_route("/facility/approve/{id}", endpoint=controller.approve_facility, methods=["PUT"])
router.add_api_route("/facility/reject/{id}", endpoint=controller.reject_facility, methods=["PUT"])
router.add_api_route("/facility/{id}", endpoint=controller.delete_facility, methods=["DELETE"])
router.add_api_route("/blood-requests", endpoint=controller.all_blood_requests, methods=["GET"])
router.add_api_route("/blood-requests", endpoint=controller.create_blood_request, methods=["POST"])
router.add_api_route("/blood-requests/{id}", endpoint=controller.update_blood_request, methods=["PUT"])
router.add_api_route("/blood-requests/{id}", endpoint=controller.delete_blood_request, methods=["DELETE"])
router.add_api_route("/blood-requests/{id}/approve", endpoint=controller.approve_blood_request, methods=["PUT"])
router.add_api_route("/blood-requests/{id}/reject", endpoint=controller.reject_blood_request, methods=["PUT"])
router.add_api_route("/blood-stock", endpoint=controller.global_blood_stock, methods=["GET"])
router.add_api_route("/blood-stock/units", endpoint=controller.blood_stock_units, methods=["GET"])
router.add_api_route("/blood-stock/add", endpoint=controller.add_blood_unit, methods=["POST"])
router.add_api_route("/blood-stock/{id}", endpoint=controller.update_blood_unit, methods=["PUT"])
router.add_api_route("/blood-stock/{id}", endpoint=controller.delete_blood_unit, methods=["DELETE"])
router.add_api_route("/camps", endpoint=controller.camps, methods=["GET"])
router.add_api_route("/camps", endpoint=controller.create_camp, methods=["POST"])
router.add_api_route("/camps/{id}", endpoint=controller.update_camp, methods=["PUT"])
router.add_api_route("/camps/{id}/status", endpoint=controller.update_camp_status, methods=["PUT"])
router.add_api_route("/camps/{id}", endpoint=controller.delete_camp, methods=["DELETE"])
router.add_api_route("/audit-logs", endpoint=controller.audit_logs, methods=["GET"])
router.add_api_route("/reports", endpoint=controller.reports, methods=["GET"])
router.add_api_route("/notifications/broadcast", endpoint=controller.broadcast_notification, methods=["POST"])
router.add_api_route("/notifications/history", endpoint=controller.notification_history, methods=["GET"])
router.add_api_route("/backup", endpoint=controller.backup_database, methods=["POST"])
router.add_api_route("/backups/list", endpoint=controller.backup_list, methods=["GET"])
